### ISSUE TITLE
idk how to open the .py file

### ISSUE THREAD

**Issue by somerandomguy249519** [TimTamCoder/KinitoPET-Python-Virtual-Assistant#2]
i opened both of the other files that were required to open the .py file, but whenever i try to open it it shows up for a split second then dissapears. anyone know how to fix this?

**Comment by TheSystemGuy1337** [comment]
Open the PY file in CMD; it may be trying to print an error.

**Comment by TheSystemGuy1337** [comment]
Actually, I looked. You are not supposed to download that PY file; it's source code. Download the one from releases.

**Comment by somerandomguy249519** [comment]
oh where is the one from the releases at

**Comment by TheSystemGuy1337** [comment]
https://github.com/TimTamCoder/KinitoPET-Python-Virtual-Assistant/releases/tag/1.0

Run the two other installers first, then run KinitoPET

**Comment by somerandomguy249519** [comment]
tysm

**Comment by TheSystemGuy1337** [comment]
No problem. Click "close issue" to mark this as done.
